version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/frontend/" 
    schedule:
      interval: "daily"
