### This docker-compose file is for local dev environment only ###
services:
  smtp4dev:
    image: rnwood/smtp4dev:3.5.0
    ports:
      - "3300:80"
      - "2525:25"
    environment:
      - ServerOptions__DisableMessageSanitisation=true

  mailservice:
    image: ghcr.io/thiws24/mailservice:dev
    environment:
      - SMTP_HOST=localhost
      - SMTP_PORT=2525
      - SMTP_USERNAME="test"
      - SMTP_PASSWORD="test"

      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=quarkus
      - KEYCLOAK_CLIENT_ID=app-service
      - KEYCLOAK_CLIENT_SECRET=secret
      - KEYCLOAK_CLIENT_USERNAME=admin
      - KEYCLOAK_CLIENT_PASSWORD=admin
      - KEYCLOAK_CLIENT_GRANT_TYPE=password

      - INVENTORY_SERVICE_URL=http://inventoryservice:8080

      - OIDC_AUTH_SERVER_URL=http://keycloak:8080
    ports:
      - "8080:8080"

  keycloak:
    image: ghcr.io/ainges/keycloak:test2
    ports:
      - 8081:8080

  inventoryservice_db:
    image: postgres:17
    environment:
      POSTGRES_DB: inventoryservicedb
      POSTGRES_USER: inventoryservicedbuser
      POSTGRES_PASSWORD: inventoryservicedbpw
    restart: unless-stopped

  inventoryservice:
    image: ghcr.io/thiws24/inventoryservice:latest
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://inventoryservice_db:5432/inventoryservicedb
      QUARKUS_DATASOURCE_USERNAME: inventoryservicedbuser
      QUARKUS_DATASOURCE_PASSWORD: inventoryservicedbpw
    ports:
      - 8083:8080
    depends_on:
      - inventoryservice_db
    restart: unless-stopped

  activemq:
    image: ghcr.io/thiws24/equipli/activemq:latest
    container_name: activemq-mailservice
    ports:
      - "61616:61616" # Port für JMS
      - "8161:8161"   # Port für die Admin-Oberfläche
    environment:
      - user=admin
      - password=admin123





