
services:
  smtp4dev:
    image: rnwood/smtp4dev:3.5.0
    ports:
      - "3300:80"
      - "2525:25"
    environment:
      - ServerOptions__DisableMessageSanitisation=true

#  mailservice:
#    image: ghcr.io/thiws24/mailservice:latest
#    ports:
#      - 8080:8080
#    environment:
#      - SMTP_HOST=${SMTP_HOST}
#      - SMTP_PORT=${SMTP_PORT}
#      - SMTP_USERNAME=${SMTP_USERNAME}
#      - SMTP_PASSWORD=${SMTP_PASSWORD}

  keycloak:
    image: ghcr.io/ainges/keycloak:test2
    ports:
      - 8081:8080

  inventoryservice_db:
    image: postgres:17
    environment:
      POSTGRES_DB: inventoryservicedb
      POSTGRES_USER: inventoryservicedbuser
      POSTGRES_PASSWORD: inventoryservicedbpw
    restart: unless-stopped

  inventoryservice:
    image: ghcr.io/thiws24/inventoryservice:latest
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://inventoryservice_db:5432/inventoryservicedb
      QUARKUS_DATASOURCE_USERNAME: inventoryservicedbuser
      QUARKUS_DATASOURCE_PASSWORD: inventoryservicedbpw
    ports:
      - 8083:8080
    depends_on:
      - inventoryservice_db
    restart: unless-stopped


