name: backend

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        service: [ inventoryservice, qrservice, reservationservice ]
        include:
          - service: inventoryservice
            webhook_var: PORTAINER_INVENTORYSERVICE_WEBHOOK_URL
          - service: qrservice
            webhook_var: PORTAINER_QRSERVICE_WEBHOOK_URL
          - service: reservationservice
            webhook_var: PORTAINER_RESERVATIONSERVICE_WEBHOOK_URL
          #- service: mailservice
          #  webhook_var: PORTAINER_MAILSERVICE_WEBHOOK_URL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Build the Maven artifact
        working-directory: backend/${{ matrix.service }}/
        run: ./mvnw package -Pprod -DskipTests

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: backend/${{ matrix.service }}/
          file: backend/${{ matrix.service }}/src/main/docker/Dockerfile.jvm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/thiws24/${{ matrix.service }}:latest

      - name: Call a webhook for Portainer
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_type: 'json'
          webhook_url: ${{ secrets[matrix.webhook_var] }}
