name: CI-mail-service

on:
  pull_request:
    branches: [ "main"]
  push:
    branches: ["47-notification-per-email-als-erinnerung"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Maven artifact mail-service
        working-directory: mail-service/
        run: ./mvnw package -Pprod -DskipTests

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: mail-service/
          file: mail-service/src/main/docker/Dockerfile.jvm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/thiws24/mail-service:latest

      - name: Call a webhook for Portainer
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_type: 'json'
          webhook_url: ${{ secrets.PORTAINER_II_WEBHOOK_URL }}
