# This is a basic workflow to help you get started with Actions

name: CI-InventoryItem

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "14-Actions-test" ]
    #pull_request:
    #branches: [ "14-service-fr-inventoryitem" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4


      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

          # Ensure QEMU is installed for cross-building
      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Maven artifact
        working-directory: iiservice/
        run: ./mvnw package -Pprod -DskipTests

      - name: Build and push multi-architecture Docker image
        working-directory: iiservice/
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f src/main/docker/Dockerfile.jvm \
            -t ghcr.io/thiws24/inventoryitemservice:latest \
            --push .