name: CI-iiservice

on:
  push:
    branches: [ "53-deployment-iiservice" ]
  #pull_request:
    #branches: [ "14-service-fr-inventoryitem" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Ensure QEMU is installed for cross-building
      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Maven artifact
        working-directory: iiservice/
        run: ./mvnw package -Pprod -DskipTests

      - name: Build and push multi-architecture Docker image
        working-directory: iiservice/
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f src/main/docker/Dockerfile.jvm \
            -t ghcr.io/thiws24/iiservice:latest \
            --push .
